title: Craig Ferguson
logo: MyPhoto1.png
description: A data analyst with experience using Excel for data analsis, SQL for data manipulation and interrogation, and Power Bi for creating data intelligence reports.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
